### PR TITLE
Creating a new setting under miscellaneous category which enables user to enable/disable the checking of new versions

### PR DESCRIPTION
**Pull request by jainsahab**
Creating a new setting under miscellaneous category which enables user to enable/disable the checking of new versions

Fixes issue #225 

@build-canaries/owners

image

### CODE REVIEW

**Comment by GentlemanHal** [comment]
Hi @jainsahab, thanks for submitting this pull request ❤️ 

Would you be able to make a few changes?

I don't think this requires a new section, would you be able to move it under the 'General Settings' that already exist.
The CheckForNewVersion component isn't required, it would be better to check the toggle directly in the hook and just not make the call.

Thanks!

**Comment by jainsahab** [comment]
Hi @GentlemanHal , 

Sure, will do that.
> would you be able to move it under the 'General Settings' that already exist.

I also thought of that, but i was thinking it will completely clean up the scheduled job from the Timer hook, otherwise it'll still be running in background without doing any extra work. Let me know what you think of this?
> The CheckForNewVersion component isn't required, it would be better to check the toggle directly in the hook and just not make the call.

**Comment by GentlemanHal** [comment]
> I also thought of that, but i was thinking this way it will completely clean up the scheduled job from the Timer hook, otherwise it'll still be running in background without doing any extra work. Let me know what you think of this?

I didn't think about that, but I don't think it's an issue. I'd rather keep the code clean than worry about a timer triggering every 24 hours that does nothing. So I'd still prefer the logic to sit in the hook for now.

**Comment by jainsahab** [comment]
Hi @GentlemanHal , Both of the feedback are now resolved, Let me know if you have any more feedbacks.

**Comment by GentlemanHal** [comment]
Instead of getting the flag in the Nevergreen component and passing to the hook, I think you should just be able to `useSelector(getToggleVersionCheck)` directly in the hook which'll help keep all the logic together.

**Comment by jainsahab** [comment]
Yes, You are right. i was trying out something on the similar lines but got this.
image

but yeah, it was due to some other reason. 😓 
It's working fine now.

**Comment by GentlemanHal** [comment]
Merged, thanks! I made a few tweaks which I committed under #225

**Pull request closed without merging**
