### PR TITLE
Broken Build Timers

### PR DESCRIPTION
**Pull request by jimmythompson**
ng

This is my attempt at resolving #82.

It shows broken builds on a timer and automatically updates them. It just uses the `lastBuildTime` element in the cc.xml, so it's nothing special. The bulk of the work is around creating a new view, called 'Display', which contains the setting to turn this feature on and off. It's off by default.

The only issue I've seen is the grid sometimes comes out of alignment. This seems to be a pre-existing issue (see gif), but it's now more likely because we have more text in each box.

As always, feedback is appreciated. :smiley:

### CODE REVIEW

**Comment by GentlemanHal** [comment]
I haven't looked at the commits closely but from the gif, this isn't a broken build timer. It's just a build timer as it's appearing for building projects as well. 

I actually prefer this, so my only issue is calling it a 'broken build timer' in the options. This should be changed to just 'build timers' :smile: 

In other news, apache have projects that have been building for over 5 hours and others that have been broken for over a month! :scream:

**Comment by jimmythompson** [comment]
The timers on projects that are building display how long it's been since the _previous_ time it was built, not how long something has been building for (that would be cool. :sob:)

To remove confusion, do you think it's better to hide timers on building projects?

**Comment by jimmythompson** [comment]
> and others that have been broken for over a month! :scream:

_"Nevergreen, a build monitor and a description of your project."_

**Comment by GentlemanHal** [comment]
Ah, interesting!

It seems to me knowing how long something has been building *for* is more useful than how long since it was last built?

If everyone agrees we should remove the current timer from building projects as you suggest, and raise a new issue about adding a 'building for' timer.

**Comment by jimmythompson** [comment]
screen shot 2015-12-16 at 09 27 34

I took a look at the alignment problem and it turns out, in a haze, I'd padded the boxes by 10px in order to stop the timer touching the edge of the box. I've changed that to 0.1em and it seems to have fixed the problem, but if any of you could take a look at it and just resize the window to check that'd be appreciated.

I've also taken out timers for building projects (see image.)

**Comment by GentlemanHal** [comment]
We automatically assume 2 characters of padding when calculating the font size, so any padding less than 0.5em shouldn't cause misalignment.

We currently do that character padding directly in [scale-text](https://github.com/build-canaries/scale-text/blob/master/index.js#L28). This is because the Nevergreen implementation was just extracted and we have not had the time to make it more generic yet.

**Comment by jimmythompson** [comment]
So what do you think, is this okay to merge? Is there anything you'd want to see changed? :smile:

**Comment by GentlemanHal** [comment]
I've been merging and checking these locally rather than use the auto merge, I just haven't had time yet. Should be able to do so over the weekend :smile:

**Pull request closed without merging**
