### PR TITLE
Document how to get going from a Git checkout

### PR DESCRIPTION
**Pull request by cburgmer**
Hey,

I'm trying to make one or two changes to nevergreen, which requires me to start from source. It took me a few minutes to realise that I needed to run `npm` and also `lein ring server-headless` (or something equivalent) to get going. I would expect that this information might help others as well. Happy to even have this in in any other form.

### CODE REVIEW

**Comment by GentlemanHal** [comment]
We have added that information to the [wiki](https://github.com/build-canaries/nevergreen/wiki/contributing), please feel free to update that page if required.

We originally added the information to the README but we found most people were just using and not developing so we removed it to make the README simpler.

Please let us know if you think having the wiki is not good enough :)

**Comment by cburgmer** [comment]
Thanks, I probably didn't check thoroughly enough. Would it be OK to simplify the "contribute" page, to just show the command, with less human text around it?

Is there a reason why there's pre-push.sh *and* develop.sh?

**Comment by joejag** [comment]
I think we should put a link to the contributing wiki page directly in the README again. We want to encourage others to hack on Nevergreen.

@cburgmer the ```develop.sh``` script is a long-lived watching type script. ```pre-push.sh``` is a single shot run. Like you say, they are mainly the same.

**Comment by GentlemanHal** [comment]
@cburgmer If you mean make it more obvious the easiest way to get started is the `develop.sh` script, then that sounds like a good update. However, if you mean listing the commands invoked by the script, such as `npm install`, then I don't think that is a good idea as the wiki will just end up out of date.

The README has been updated with slightly different information than your patch, so it would be great if you could check give it a look see again.

Once you're happy with the README and wiki could you let us know or just close this issue, thanks!

**Comment by cburgmer** [comment]
README looks good. Thanks!

**Pull request closed without merging**
