### PR TITLE
lein environ update

### PR DESCRIPTION
**Pull request by brydoncheyney**
the existing environ/environ.lein hooks are over three years old and the updated lein-environ plugin auto-configures hooks without the overhead of the lein :hooks config.

this is far cleaner, reflect current intent and allows consistent versioning across the environ and lein-environ projects.

tested against the develop.sh script, project.clj configuration and also building an uberjar...

    [nevergreen] vi project.clj
      ...
      :env {:port 4000}
       ...
    [nevergreen] lein run
    [nevergreen] lein uberjar && java -jar target/nevergreen-standalone.jar
    [nevergreen] PORT=4000 java -jar target/nevergreen-standalone.jar

all seems good - though using node/npm under ubuntu provides its own 'interesting quirks' such as requiring the promise package removed in an earlier commit...

would be interested to see if the snap deployment still works?

[also updated compojure and ring-defaults to latest versions... because why not]

### CODE REVIEW

**Comment by joejag** [comment]
Thanks @brydoncheyney. This works on my machine.

@GentlemanHal merge if you are happy

**Comment by GentlemanHal** [comment]
Not going to lie, not really sure what this patch actually gives us or how we are using lein environ hooks at the moment... Was this something you originally added @joejag?

Does this change allow us to update to lein 2.6.1?

Am happy to merge if everything still works and this is the correct way of doing it now, but it would be nice to get some more info :)

**Comment by GentlemanHal** [comment]
This has been merged and everything seems to be working fine

**Comment by brydoncheyney** [comment]
I'm using lein 2.6.1 so... yes?

**Pull request closed without merging**
